### ISSUE TITLE
Purpose and Progress

### ISSUE THREAD

**Issue by stefanKuijers** [weixin/WeFlow#85]
My knowledge in Chineese is not that great so I might ask some questions that have an obvious answer.

1) Is there any change of you guys building an English version of this?
2) Is this tool specifically made for the company you guys work at or is it intented for broader usage?

3) @littledu Did you find a way to auto-compile for cross platform or are you building on each platform manually?

Thanks in advance!

**Comment by hzlzh** [comment]
It's OK for your English issues, here are some answers you may want to know.

1) We've got a long term plan in supporting English at first, but since we most of WeFlow users are here in china, that plan was hold. So you may fork WeFlow repo and translate [App GUI text](https://github.com/weixin/WeFlow/tree/master/src) and re-compile a new App.

2)  We made this WeFlow for F2E guys building there web projects with our experience and habits, so if you want to change some flow or GUI, just fell free to fork it. If you got so many places to change, maybe [tmt-workflow](https://github.com/weixin/tmt-workflow) is a better choice.

3) We've got a flow to built App automatically using [appveyor.com for Windows]() and [travis-ci.org for Linux](). You can check the command step by step in there config files [appveyor.yml](https://github.com/weixin/WeFlow/blob/master/appveyor.yml) and [.travis.yml](https://github.com/weixin/WeFlow/blob/master/.travis.yml)

Also we use a Cloud CDN(qiniu.com) to fatch those compiled result above, you may use [AWS](https://aws.amazon.com/) instead. 



If you got any other questions, feel free to reply.

**Comment by stefanKuijers** [comment]
Thank you for your answers. I have forked the project and an very curious to look into how you build this app. 

Just as a hobby project I have build something similar to this about a year ago but got stuck on the recompiling (lib-sass) and fixing it cross platform. 

I'm not sure or I will get to translating as I would like to try to continue my own development. 

Good luck with the workflow app. It looks awesome.

**Comment by hzlzh** [comment]
That's great! :)

**Comment by littledu** [comment]
Maybe you will like it: https://github.com/littledu/node-sass-prebuild-for-electron @stefanKuijers

**Comment by stefanKuijers** [comment]
@littledu. It's awesome. I have never used appveyor but if I see it right this might actually answer my [other question](https://github.com/weixin/WeFlow/issues/87) Lets move the discussion over there.
